京都大学所属であるかを明文化 / 学生番号を追加
kmc-jp/guildbook pull request #149
Opened 2023-04-30 05:23 UTC by walnuts1018

- 京都大学所属であるかのSelectBoxを追加しています
  - 京都大学の場合、学部学科のSelectBox、学生番号、学年の欄を表示
  - そうでなければ所属のTextBoxを表示

![2023-04-30_14h22_23](https://user-images.githubusercontent.com/60650857/235337084-12e9269b-4f2f-4b30-9ba0-dba90afc1819.png)
![2023-04-30_14h22_31](https://user-images.githubusercontent.com/60650857/235337085-a1a85eaa-8e9e-439a-aa70-f221a8c07e9d.png)

- schemaの追加は、`x-kmc-IsKUMember` `x-kmc-KUDepartment` `x-kmc-KUStudentNumber` の3つです

2023-04-30 06:36 UTC, walnuts1018 commented
とりあえずということで、csv exportに関してはできてないです。

2023-04-30 07:25 UTC, hiromi-mi reviewed
haml・Rubyに関しては知識がないため確認できていませんが、少しだけ確認しました。

2023-04-30 07:25 UTC, hiromi-mi commented on schema/kmc.schema
> +  SYNTAX 1.3.6.1.4.1.1466.115.121.1.7 )
取れる値を単一に限定すると無用なトラブルが避けられそうです。

```suggestion
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.7
  SINGLE-VALUE )
```

2023-04-30 07:27 UTC, walnuts1018 commented on schema/kmc.schema
> +  SYNTAX 1.3.6.1.4.1.1466.115.121.1.7 )
複数値を取れるんですね...なるほど
ありがとうございます。

2023-05-02 04:02 UTC, hiromi-mi commented
(hamlとRubyについては私はくわしくないので、どなたか別の方にお願いできると嬉しいです)

2023-05-02 08:23 UTC, hanazuki requested changes

2023-05-02 08:23 UTC, hanazuki commented on lib/view_helpers.rb
> +        if (showDefault) then
Rubyでは変数名はsnake_caseにするのが一般的なので揃えてほしいです
またifに括弧はいらないです（改行する場合はthenもいらないです）
```suggestion
    def select_userattr(user, attr, values, show_default, opt = {})
      opt[:class] ||= 'form-select'
      haml_tag :select, {name: attr}.merge(opt) do
        if show_default
```

2023-05-02 08:23 UTC, hanazuki commented on views/edit.haml
> +-kuDepartments={"工学部情報学科": "工学部情報学科", "工学部電気電子工学科": "工学部電気電子工学科", "工学部物理工学科": "工学部物理工学科", "工学部地球工学科": "工学部地球工学科", "工学部建築学科": "工学部建築学科", "工学部工業化学科": "工学部工業化学科", "理学部": "理学部", "医学部医学科": "医学部医学科", "医学部人
これはLDAPの属性値として現れる文字列からHTMLに表示する文字列のマップなので，キーをシンボルにしないで，`{"工学部情報学科" => "工学部情報学科", ...}` のような持ち方にしたいですね
そうすると，`select_userattr`の比較をしているところでto_symする必要もなくなります

2023-05-02 08:23 UTC, hanazuki commented on views/edit.haml
> +          - select_userattr user, 'x-kmc-IsKUMember', {"TRUE": "京都大学", "FALSE": "その他"} , false, id: 'edit-is-kyoto-university'
kuDepartmentsと同じ理由で
```suggestion
          - select_userattr user, 'x-kmc-IsKUMember', {"TRUE" => "京都大学", "FALSE" => "その他"} , false, id: 'edit-is-kyoto-university'
```

2023-05-02 08:23 UTC, hanazuki commented on lib/view_helpers.rb
> +        end
cf. `views/edit.haml`へのコメント
```suggestion
        current_value = user[attr].first
        values.each do |k, v|
          selected = v == current_value
          haml_tag :option, value: k, selected: selected do haml_concat v end
        end
```

2023-05-02 09:13 UTC, walnuts1018 commented
ありがとうございます。確認修正します。

2023-05-02 10:44 UTC, walnuts1018 commented
すべて修正しました。
こちらのテスト環境では正常に動いていそうです。

2023-05-02 11:06 UTC, hanazuki approved these changes

2023-05-02 13:50 UTC, merged

2023-05-02 14:19 UTC, hanazuki commented on lib/view_helpers.rb
> +          selected = v == current_value
`selected = k == current_value` がただしかったです